### ISSUE TITLE
Cannot find module 'drop-zone' or its corresponding type declarations.

### ISSUE THREAD

**Issue by ayham-al-adm** [darknessnerd/drop-zone#33]
I have a problem with using typescript with drop-zone
I already signed dropzone-vue component inside main.ts file
but I get this error inside my component 
Cannot find module 'drop-zone' or its corresponding type declarations.
![image](https://user-images.githubusercontent.com/48181010/183038587-04abba15-98f0-4d97-80d2-0d5cfefdacf9.png)

**Comment by darknessnerd** [comment]
`import DropZone from 'dropzone-vue';

// optionally import default styles
import 'dropzone-vue/dist/dropzone-vue.common.css';

createApp(App)
  .use(DropZone)
  .mount('#app')`

you need to import it and use it as a Plugin.

**Comment by ayham-al-adm** [comment]
@darknessnerd yep, I did and it worked correctly
thanks a lot
