### ISSUE TITLE
No event to capture ajax response on success

### ISSUE THREAD

**Issue by johndscanx** [darknessnerd/drop-zone#8]
Hello there! 

Is there a way to capture the ajax response on successful upload? I don't find it in the documentation. Thanks!

**Comment by darknessnerd** [comment]
can you try this ? 

```html
<DropZone @uploaded="uploaded">
```

Called when a file is going to be uploaded.

```html
<DropZone @sending="sending">
```

**Comment by markdegrootnl** [comment]
the uploaded event does not contain the AJAX response

**Comment by ingageco** [comment]
+1 for needing to capture the ajax response on success. it's useful for getting the upload URL.
